version: '3'

services:
  # Main robot controller service
  robot-controller:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: robot-controller
    ports:
      - "5000:5000"  # Web interface port
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is unbuffered
    # Use privileged mode to access GPIO pins and hardware
    privileged: true
    # Mount the host's /dev directory to access hardware
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # GPIO memory access
      - "/dev/i2c-1:/dev/i2c-1"      # I2C bus for servo controller
    volumes:
      - "./templates:/app/templates"  # Mount templates directory for web interface
      - "./servo_calibration.py:/app/servo_calibration.py"  # Mount calibration file if it exists 